---
title: "Tests CRS with sf"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: "cosmo"
    highlight: tango
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load packages and data

```{r}

# 1. Load packages ----

library(tidyverse) # Core tidyverse packages
library(sf)
sf_use_s2(FALSE) # Switch from S2 to GEOS

# 2. Source functions ----

source("../code/function/theme_map.R")
source("../code/function/graphical_par.R")

```

# Global Pacific map

```{r}

# 1. Define changed CRS ----

# 1.1 Define the CRS --

crs_selected <- "+proj=eqc +lat_ts=0 +lat_0=0 +lon_0=160 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs"

# 1.2 Define the offset --

correction_offset <- 180 - 160 # Here 160 is the same value than +lon_0 from crs_selected

# 1.3 Define a long and slim polygon that overlaps the meridian line --

correction_polygon <- st_polygon(x = list(rbind(c(-0.0001 - correction_offset, 90),
                                                c(0 - correction_offset, 90),
                                                c(0 - correction_offset, -90),
                                                c(-0.0001 - correction_offset, -90),
                                                c(-0.0001 - correction_offset, 90)))) %>%
  st_sfc() %>%
  st_set_crs(4326)

# 2. Load background maps ----

data_map <- read_sf("../data/01_natural-earth-data/ne_10m_land/ne_10m_land.shp") %>% 
  st_transform(crs = 4326) %>% 
  st_difference(correction_polygon) %>% 
  st_transform(crs_selected)

# 3. Economic Exclusive Zones ----

data_eez <- read_sf("../data/02_eez/World_EEZ_v11_20191118/eez_boundaries_v11.shp") %>% 
  st_transform(crs = 4326) %>% 
  st_difference(correction_polygon) %>% 
  st_transform(crs_selected)

# 4. Bathymetry ----

# 4.1 List path of shapefiles --

list_shp <- list.files(path = "../data/01_natural-earth-data/ne_10m_bathymetry_all/", pattern = ".shp", full.names = TRUE)

# 4.2 Combine shapefiles --

data_bathy <- map_dfr(list_shp, ~st_read(., quiet = TRUE)) %>% 
  mutate(color = case_when(depth == 0 ~ "#e1f5fe",
                           depth == 200 ~ "#b3e5fc",
                           depth == 1000 ~ "#81d4fa",
                           depth == 2000 ~ "#4fc3f7",
                           depth == 3000 ~ "#29b6f6",
                           depth == 4000 ~ "#03a9f4",
                           depth == 5000 ~ "#039be5",
                           depth == 6000 ~ "#0288d1",
                           depth == 7000 ~ "#0288d1",
                           depth == 8000 ~ "#0277bd",
                           depth == 9000 ~ "#01579b",
                           depth == 10000 ~ "black")) %>% 
  mutate(color = fct_reorder(color, depth)) %>% 
  st_transform(crs = 4326) %>% 
  st_difference(correction_polygon) %>% 
  st_transform(crs_selected)

# 5. Create the tropics ----

data_tropics <- tibble(long = c(-180, 180, -180, 180, -180, 180), 
                       lat = c(0, 0, 23.43656, 23.43656, -23.43656, -23.43656), 
                       tropic = c("equator", "equator", "cancer", "cancer", "capricorne", "capricorne")) %>% 
  st_as_sf(coords = c("long", "lat"), crs = 4326) %>% 
  group_by(tropic) %>% 
  summarise() %>% 
  st_cast("LINESTRING") %>% 
  st_difference(correction_polygon) %>% 
  st_transform(crs_selected)

# 6. Make the map ----

ggplot() +
  # Bathymetry
  geom_sf(data = data_bathy, aes(fill = color), color = NA) +
  # EEZ
  geom_sf(data = data_eez, color = "white") +
  # Tropics
  geom_sf(data = data_tropics, linetype = "dashed", color = "black") +
  # Background map
  geom_sf(data = data_map, fill = col_fill_map, col = col_color_map) +
  coord_sf(ylim = c(-4000000, 4000000), xlim = c(-3500000, 11000000), expand = FALSE) +
  scale_fill_identity() +
  theme(panel.border = element_rect(size = 1, fill = NA, colour = "black"))

# 7. Save the map ----

ggsave(filename = "../figs/01_global-map-pacific.png", width = 10, height = 6, dpi = 600)

```

# Reproducibility

```{r reprod}

# 1. Reproducibility ----

sessionInfo()

```

---
Jeremy WICQUART | jeremywicquart@gmail.com | `r format(Sys.time())`